### ISSUE TITLE
Allow custom landing pages

### ISSUE THREAD

**Issue by andrepintado** [dreamshaper/dreamshaper#12]

**Comment by andrepintado** [comment]
- main page
- /login
- /signup
- /resetting/request
- /resetting/check-email

cores
logótipo
texto

**Comment by pqueiro** [comment]
**Objective:** enable custom landing pages for certain paying customers. We'll have to slightly rethink current org page packages (which include landing, signup, login, perhaps recover?) because of unnecessary content eg how it works. Also, current designs will have to be simplified or at least a new flexible simple design created (ie without gradients, parallax effects, etc).

**Use Case:** multiple clients want to adjust Dreamshaper pages to their own colour scheme / image (eg, Junior Achievement). This is acceptable within strict parameters (limited changes, credit to DS where it is due, etc). In the future, this will be part of our commercial offering (sales staff will love it...).

**Further reading:** (brainstorming session may be required?)

Colour schemes will have to be flexible and adjustable. This means designing a new homepage with a set of ~5 colours for fonts, background, links, accents, etc (must get designer input on this). Whenever we want to set up a new one, we will need to select the appropriate set of colours (in such a way that the final product works!) and adjust relevant CSS values.

Four other elements will also be customizable in the landing page:

1. URL (in format **xyz**.dreamshaper.com)
2. Title (eg UNAD | DreamShaper)
3. Slogan (eg Bienvenido a Emprendimiento practico!)
4. Up to 3 lines of text on the landing page

**Colours + 4 elements should be all that is customizable.** More than this and we run the risk of getting sidetracked or taking too long to deploy a new org.

**To-dos:**
- [ ] draw up wireframes for new, flexible landing page
- [ ] define CSS adjustment method & process (does it require constant designer attention? Who sets the colour scheme, us or client?)
- [ ] adjust relevant org deployment files to reflect adjustment
- [ ] test / deploy?
